---
title: "Project_No_Shows"
author: "Pearl Muensterman"
date: "12/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(olsrr)
library(MASS)
```

Lots of types of vehicles, too many dummy variables for a small data set
Filter out shows

```{r}
data2 <- read_excel("clean_amusement_data.xlsx")

str(data)
data2 <- mutate(data2, main = if_else(main == "No", 0, 1))
data2 <- mutate(data2, story = if_else(story == "No", 0, 1))
data2 <- mutate(data2, Indoor = if_else(location == "Indoor", 1, 0),
                     Outdoor = if_else(location == "Outdoor", 1, 0))
data_no_show <- filter(data2, vehicle != "Show")
data_no_show <- dplyr::select(data_no_show, -location, -name, -vehicle)

ggplot(data_no_show) +
  geom_histogram(aes(x = length))
```

All Possible
```{r}
park_model <- lm(wait ~ ., data = data_no_show)
all_poss_model2 <- ols_step_all_possible(park_model)
which.max(all_poss_model2$adjr)
all_poss_model2[27824,]$adjr
all_poss_model2[27824,]$predictors
which.min(all_poss_model2$cp)
all_poss_model2[576,]$predictors
```
best r^2: main age length interest_teen interest_ya interest_senior story sense Indoor Outdoor
best r^2 = 0.4923444
best cp: length interest_ya story Outdoor

```{r}
full_mod <- lm(wait ~ ., data = data_no_show)
base_mod <- lm(wait ~ 1, data = data_no_show)
forward_mod <- stepAIC(base_mod, direction = "forward", trace = FALSE, 
                       scope = list(upper = full_mod, lower = base_mod))
forward_mod$anova
```
Outdoor, interest_ya, length, story

```{r}
backward_mod <- stepAIC(full_mod, direction = "backward", trace = FALSE, 
                       scope = list(upper = full_mod, lower = base_mod))
backward_mod$anova
```
length, interest_ya, story, Outdoor

```{r}
step_mod <- stepAIC(full_mod, direction = "both", trace = FALSE, 
                       scope = list(upper = full_mod, lower = base_mod))
step_mod$anova
```
length, interest_ya, story, Outdoor

```{r}
mod_show <- lm(wait ~ length + interest_ya + story + Outdoor, data = data_no_show)
summary(mod_show)
```


